# Joystic configuration for Logitech F310 gamepad
axes_map:
  roll: 3
  pitch: 2
  yaw: 0
  throttle: 1
axes_scale:
  roll: 0.5
  pitch: 0.5
  yaw: 0.5
  throttle: 0.5
button_map:
  takeoff: 0
  land: 1
  enable: 2
