TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /odom

 # Trajectory
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5

 # Robot
 max_vel_x: 0.2
 max_vel_x_backwards: 0.2
 max_vel_y: 0.2
 max_vel_theta: 1.0
 acc_lim_x: 2.5
 acc_lim_y: 2.5
 acc_lim_theta: 3.2
 footprint_model:
   type: "polygon"
   vertices: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]

 # GoalTolerance
 xy_goal_tolerance: 0.5